<?php

function localist_pane_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && ($plugin_type == 'content_types')) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Helper function for decoding JSON.
 *
 * @param string $uri
 *   The JSON feed.
 *
 * @return array
 *   The retrieved data.
 */
function _localist_pane_decode($uri) {
  $decode_content = drupal_http_request($uri);
  $decode_array = drupal_json_decode($decode_content->data);
  return $decode_array;
}
